DevExpress/testcafe-gh-page-assets

- src/_plugins/auto-anchors.rb
- src/_sass/_base.scss
DevExpress/testcafe#312
\cc @DevExpress/tescafe-docs
> Docs: Generate anchors from headers and add a way to copy links to them

- src/_plugins/auto-anchors.rb
- src/_plugins/md-links-to-html-links.rb
\cc @MargaritaLoseva @inikulin 
first part of devexpress/testcafe#311
> Add a converter that transforms MD links to HTML links

- src/_sass/_layout.scss
Agreed with Dmitry Kharkov
/cc @inikulin, @VasilyStrelyaev
> Header style changed

- src/_sass/_base.scss
- src/_sass/_layout.scss
- src/css/example-page.scss
- src/css/main.scss
- src/example/index.html
- src/example/thank-you.html
Almost as the designer painted
fixes DevExpress/testcafe#506
> Introduce the Example page

- src/_includes/head.html
- src/css/landing-page.scss
fixes https://github.com/DevExpress/testcafe-gh-page-assets/issues/13
> Make the landing page load faster

- src/_config.yml
- src/_includes/head.html
A couple of small things.
* Google Analytics
* Improved page titles
* Landing page meta description
* Auto-generated sitemap
> SEO and Analytics

- src/_includes/nav-menu-folder.html
- src/_includes/nav-menu-item.html
- src/css/example-page.scss
- src/example/index.html
> Support for a new (more reasonable) TOC structure and native select for the example page

- src/css/landing-page.scss
Updated the landing page banner design according to http://take.ms/Ei8a5
Also got rid of all places where the font family fallback chain is overridden (BTW is it right?).
> Landing page banner updated

- src/_includes/head.html
> Fix protocol for DevExpress CDN content

- src/_includes/head.html
- src/css/main.scss
applied @helen-dikareva 's fix
pls check once again on mobile
> Fix navigation menu on mobile

- src/css/landing-page.scss
> Add animation to the landing page

- src/_includes/head.html
- src/_includes/header.html
- src/_includes/nav-menu.html
- src/_sass/_layout.scss
- src/css/main.scss
see http://strelyaev-w8:8080/testcafe/documentation/using-testcafe/
> [docs] Introduce the top menu for documentation

- src/_includes/head.html
> Fix documentation layout on mobile

- src/_includes/head.html
- src/css/main.scss
http://strelyaev-w8:8080/testcafe/documentation/getting-started/
> Fixed content jumping and increased min width

- src/_includes/nav-menu-item.html
- src/_includes/nav-menu.html
- src/_plugins/md-links-to-html-links.rb
> Rename index.md to README.md

- src/_config.yml
> Rename jekyll's deprecated config option

- src/_layouts/faq.html
- src/_sass/_layout.scss
> Prepare layout for an FAQ page

- src/_sass/_layout.scss
- src/publications/index.html
> Prepare for the publication list

- src/_includes/footer.html
- src/_includes/head.html
- src/_includes/header.html
- src/_includes/nav-menu.html
- src/_layouts/docs.html
- src/_layouts/landing.html
- src/_sass/_base.scss
- src/_sass/_layout.scss
- src/blog/index.html
- src/css/gallery.css
- src/css/landing-page.scss
- src/css/main.scss
- src/publications/index.html
- src/scripts/gallery.js
- src/scripts/landing-page.js
http://strelyaev-w8:8080/testcafe/
> Introduce the new landing page

- src/_layouts/landing.html
- src/scripts/landing-page.js
> [docs] Attach GA to Get Started button and tweak the Algolia drop-down width

- src/css/gallery.css
> Make images less blurry

- src/_includes/head.html
- src/_includes/header.html
- src/_sass/_layout.scss
Fixes https://github.com/DevExpress/testcafe/issues/1894, https://github.com/DevExpress/testcafe/issues/1892 and https://github.com/DevExpress/testcafe/issues/1891
\cc @DevExpress/testcafe-docs
> Fixes #1894, #1892 and #1891

- src/_includes/head.html
- src/css/main.scss
\cc @AndreyBelym @AlexanderMoskovkin 
fixes https://github.com/DevExpress/testcafe/issues/1972
Solved the problem by changing the font. We all (incl the designer) agreed that DejaVu Sans was horrible.
> Changed the font for Linux

- src/_includes/head.html
- src/_sass/_layout.scss
- src/css/landing-page.scss
- src/css/main.scss
Fix the problem in DevExpress/testcafe#1972 in Firefox
Eventually had to increase min-width (crap).
\cc @kirovboris @AlexanderMoskovkin
> [docs] Fix broken nav menu in Firefox on Linux

- src/scripts/landing-page.js
> Remove an unnecessary DXPopup

- src/example/index.html
> Example page - remove redundant spaces

- src/blog/index.html
- src/publications/index.html
> Add page titles

- src/_includes/footer.html
> Update the footer text

- src/_includes/head.html
- src/css/gallery.css
- src/css/landing-page.scss
- src/scripts/tweet-gallery.js
Preview: http://strelyaev-w8:8080/testcafe/
> Introduce the tweet gallery

- src/css/landing-page.scss
- src/scripts/tweet-gallery.js
> Tweet gallery arrows margin fixed

- src/_includes/header.html
- src/css/landing-page.scss
- src/scripts/landing-page.js
Preview: http://strelyaev-w8:8080/testcafe/
> Add the Rapid Test Development section

- src/_layouts/post.html
> Disable comments in Release Notes

- src/_includes/footer.html
> Add a link to the privacy policy

- src/_includes/cookie-notice.html
- src/_includes/doc-search.html
- src/_includes/head.html
- src/_layouts/landing.html
- src/_sass/_layout.scss
- src/scripts/cookie-notice.js
> Add a cookie notice

- src/css/thank-you.scss
- src/example/thank-you.html
\cc @kirovboris 
`min-width` is not required on the Thank you page - it only brings mess
> Fix thank you page

- src/_includes/head.html
- src/css/landing-page.scss
Preview at: http://strelyaev-w8:8080/testcafe/
> Add Studio promo

- src/_sass/_layout.scss
For this [PR](https://github.com/DevExpress/testcafe/pull/2604)
> Fix for search panel

- src/_includes/header.html
> [docs] Add Analytics for top-level Studio link

- src/_sass/_layout.scss
- src/scripts/cookie-notice.js
\cc @kirovboris @helen-dikareva 
An urgent fix for iPad
> iPad desktop styles fix

- src/_config.yml
> Add a redirect from the docs root page

- src/_plugins/important-note.rb
- src/_plugins/wrap-tables.rb
\cc @AndreyBelym  @helen-dikareva 
A fix for documentation tests by @AndreyBelym (thanks to him!).
> Fix documentation tests

- src/css/support-page.mobile.scss
- src/support/index.html
> Fix a minor bug with the popup on the mobile support page

- src/_plugins/videos.rb
- src/_sass/_base.scss
- src/css/landing-page.mobile.scss
- src/css/landing-page.scss
- src/scripts/landing-page.js
(let's not merge this until just before the `1.0.0` release)
> Prepare the landing page for Live Mode

- src/_includes/head.html
- src/_layouts/docs.html
The article: https://github.com/DevExpress/testcafe/pull/4626
> Add styles for the How It Works article

- src/_includes/community-content-item.html
- src/_includes/pub-preview.html
- src/community/index.html
- src/courses/index.html
- src/css/community.scss
This addresses @andnaz's remarks.
See: https://github.com/DevExpress/testcafe/pull/4906
> Community content - Add links to source home pages

- src/example/index.html
required for [testcafe#5706](https://github.com/DevExpress/testcafe/pull/5706)
> Add shadow dom to example page

- src/_includes/head.html
- src/_includes/header.html
- src/css/banner.mobile.scss
- src/css/banner.scss
- src/css/docs.scss
Reverts DevExpress/testcafe-gh-page-assets#103
> Revert "[docs] Remove the survey banner"

- src/_includes/head.html
- src/_layouts/docs.html
We have to modify hard-coded paths to force Why TestCafe looks like How It Works w/o the ugly left margin.
> Fix Why TestCafe

- src/_layouts/roadmap.html
is required for [DevExpress/testcafe#5960](https://github.com/DevExpress/testcafe/pull/5960)
see [comment](https://github.com/DevExpress/testcafe/pull/5960#issuecomment-779761775)
> Create roadmap layout
